namespace Make;

using System.Text;
using MiniZinc.TestSpec;
using MiniZinc.TestSpec.Model;
using static CodeBuilder;

/// <summary>
/// Emits one xUnit integration-test class per libminizinc suite from the
/// <see cref="TestCase"/> model produced by <see cref="YamlSpecParser"/>.
///
/// Only solve-style cases produce tests: a single expected solution becomes a
/// <c>RunSolveTest</c>, multiple expected solutions become a
/// <c>RunAnySolutionTest</c>. Compile / output-model / check-against /
/// unsatisfiable / error cases have no runtime support and are skipped.
/// </summary>
public static class ClientTestsBuilder
{
    public static string Build(IReadOnlyList<TestCase> tests, string className)
    {
        var cb = new CodeBuilder();

        using (cb.BlockComment())
        {
            cb.WriteLn("<auto-generated>");
            cb.WriteLn("This file has been auto generated by the following command:");
            cb.WriteLn("dotnet run --project make -- --make-client-tests");
            cb.Write("</auto-generated>");
        }

        cb.WriteLn("#nullable enable");
        cb.WriteLn("using Xunit;");
        cb.WriteLn("namespace MiniZinc.Tests;");
        cb.NewLine();
        cb.Block($"public class {className} : IntegrationTests");
        cb.NewLine();

        // A single .mzn file can contribute several test documents that share
        // the same (path, solver); track emitted names so each method is unique.
        var usedNames = new HashSet<string>(StringComparer.Ordinal);
        foreach (var testCase in tests)
            WriteTestCase(cb, testCase, usedNames);

        return cb.ToString();
    }

    private static void WriteTestCase(CodeBuilder cb, TestCase testCase, HashSet<string> usedNames)
    {
        if (testCase.Kind != TestKind.Solve || testCase.SkipReason is not null)
            return;

        // Translate the expected results into a list of DZN solution strings.
        // A non-solve expectation (unsat/error) means there is nothing to
        // compare against, so the case is skipped entirely.
        var solutions = new List<string>();
        foreach (var expected in testCase.Expected)
        {
            switch (expected)
            {
                case ExpectedSolution s:
                    AddSolution(solutions, s.Solution);
                    break;
                case ExpectedSolutionSet set:
                    foreach (var sol in set.Solutions)
                        AddSolution(solutions, sol);
                    break;
                case ExpectedAllSolutions all:
                    foreach (var sol in all.Solutions)
                        AddSolution(solutions, sol);
                    break;
                default:
                    // Unsatisfiable / error / compile / output-model etc.
                    return;
            }
        }

        var quotedPath = Quote(testCase.Path);
        var quotedArgs = Quote(OptionRenderer.Render(testCase.Options));

        var solvers = testCase.Solvers is { Count: > 0 } sv ? sv : new[] { "gecode" };
        IReadOnlyList<string?> extraFiles =
            testCase.ExtraFiles is { Count: > 0 } e ? (IReadOnlyList<string?>)e : new string?[] { null };

        foreach (string testSolver in solvers)
        {
            var (solverId, solverEnabled) = GetSolverInfo(testSolver);
            if (!solverEnabled)
                continue;

            var quotedSolver = Quote(solverId);
            foreach (string? extraFile in extraFiles)
            {
                string quotedExtraFile = Quote(extraFile);
                var testName = UniqueName(usedNames, GetTestName(testCase.Path, testSolver));
                cb.Attribute(
                    "Fact",
                    $"DisplayName = {Quote($"{testCase.Path} {solverId}")}",
                    "Timeout = 10_000"
                );
                using var _ = cb.Function($"public async Task {testName}");
                cb.Declare("string", "solver", quotedSolver);
                cb.Declare("string?", "args", quotedArgs);
                cb.Declare("string?", "extraFile", quotedExtraFile);

                if (solutions.Count > 1)
                {
                    var arr = '[' + string.Join(",", solutions.Select(CsString)) + ']';
                    cb.Declare("string[]", "solutions", arr);
                    cb.WriteLn($"await RunAnySolutionTest({quotedPath},solver,args,extraFile,solutions);");
                }
                else
                {
                    var quoted = solutions.Count == 1 ? CsString(solutions[0]) : "null";
                    cb.Declare("string?", "solution", quoted);
                    cb.WriteLn($"await RunSolveTest({quotedPath},solver,args,extraFile,solution);");
                }
            }
        }
    }

    private static void AddSolution(List<string> solutions, Solution solution)
    {
        var dzn = SolutionDzn.Render(solution);
        if (dzn is not null)
            solutions.Add(dzn);
    }

    /// Emit a DZN solution as an escaped, single-line C# string literal.
    private static string CsString(string s)
    {
        var sb = new StringBuilder();
        sb.Append('"');
        foreach (char c in s)
        {
            switch (c)
            {
                case '"':
                    sb.Append("\\\"");
                    break;
                case '\\':
                    sb.Append("\\\\");
                    break;
                case '\n':
                    sb.Append("\\n");
                    break;
                case '\r':
                    sb.Append("\\r");
                    break;
                case '\t':
                    sb.Append("\\t");
                    break;
                default:
                    sb.Append(c);
                    break;
            }
        }
        sb.Append('"');
        return sb.ToString();
    }

    private static string UniqueName(HashSet<string> used, string name)
    {
        if (used.Add(name))
            return name;
        for (int i = 2; ; i++)
        {
            var candidate = $"{name}_{i}";
            if (used.Add(candidate))
                return candidate;
        }
    }

    private static string GetTestName(string path, string solver)
    {
        var name = path.Replace(".mzn", "");
        name = name.Replace("/", "_");
        name = name.Replace("-", "_");
        name = name.Replace(".", "");
        name = $"test_{name}_{solver}";
        return name;
    }

    private static (string id, bool enabled) GetSolverInfo(string solver) =>
        solver switch
        {
            "cbc" => ("coin-bc", true),
            "scip" => ("scip", false),
            "gurobi" => ("gurobi", false),
            "gecode_presolver" => ("gecode_presolver", false),
            _ => ("gecode", true),
        };
}
