/*
<auto-generated>
This file has been auto generated by the following command:
dotnet run --project ./build/Make/Make.csproj --make-client-tests
</auto-generated>
*/
#nullable enable

public class ClientErrorTests : IClassFixture<ClientFixture>
{
	private readonly MiniZincClient MiniZinc;
	private readonly ITestOutputHelper _output;

	public ClientErrorTests(ClientFixture fixture, ITestOutputHelper output)
	{
		MiniZinc = fixture.MiniZinc;
		_output = output;
	}

	async Task Test(string path, string solver, string? errorMessage, string? errorRegex, params string[] args)
	{
		_output.WriteLine(path);
		_output.WriteLine(new string('-',80));
		var model = Model.FromFile(path);
		_output.WriteLine(model.SourceText);
		_output.WriteLine(new string('-',80));
		foreach (var warn in model.Warnings)
		{
			_output.WriteLine(warn);
		}

		var options = SolveOptions.Create(solverId:solver);
		options = options.AddArgs(args);

		var result = await MiniZinc.Solve(model, options);
		result.IsSuccess.Should().BeFalse();

		if (errorRegex is not null)
		{
			result.Error.Should().MatchRegex(errorRegex);
		}


		else if (errorMessage is not null)
		{
			result.Error.Should().Be(errorMessage);
		}

	}

	[Fact(DisplayName="unit/compilation/assert_dbg_flag.mzn")]
	public async Task test_solve_unit_compilation_assert_dbg_flag()
	{
		var path = "unit/compilation/assert_dbg_flag.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = null;
		await Test(path, solver, errorMessage, errorRegex,"--debug");
	}

	[Fact(DisplayName="unit/compilation/time_limit.mzn")]
	public async Task test_solve_unit_compilation_time_limit()
	{
		var path = "unit/compilation/time_limit.mzn";
		var solver = "gecode";
		string? errorMessage = "time limit reached";
		string? errorRegex = null;
		await Test(path, solver, errorMessage, errorRegex,"--time-limit 1");
	}

	[Fact(DisplayName="unit/general/array_access_out_of_bounds_1.mzn")]
	public async Task test_solve_unit_general_array_access_out_of_bounds_1()
	{
		var path = "unit/general/array_access_out_of_bounds_1.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = ".*array access out of bounds, array `x' has index set A..B, but given index is C.*";
		await Test(path, solver, errorMessage, errorRegex);
	}

	[Fact(DisplayName="unit/general/array_access_out_of_bounds_2.mzn")]
	public async Task test_solve_unit_general_array_access_out_of_bounds_2()
	{
		var path = "unit/general/array_access_out_of_bounds_2.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = ".*array access out of bounds, array `x' is empty.*";
		await Test(path, solver, errorMessage, errorRegex);
	}

	[Fact(DisplayName="unit/general/array_access_record_out_of_bounds.mzn")]
	public async Task test_solve_unit_general_array_access_record_out_of_bounds()
	{
		var path = "unit/general/array_access_record_out_of_bounds.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = ".*array access out of bounds.*";
		await Test(path, solver, errorMessage, errorRegex);
	}

	[Fact(DisplayName="unit/general/array_access_tuple_out_of_bounds.mzn")]
	public async Task test_solve_unit_general_array_access_tuple_out_of_bounds()
	{
		var path = "unit/general/array_access_tuple_out_of_bounds.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = ".*array access out of bounds.*";
		await Test(path, solver, errorMessage, errorRegex);
	}

	[Fact(DisplayName="unit/general/enum_out_of_range_1.mzn")]
	public async Task test_solve_unit_general_enum_out_of_range_1()
	{
		var path = "unit/general/enum_out_of_range_1.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = ".*declared domain of `x' is {A}, but assigned value is B.*";
		await Test(path, solver, errorMessage, errorRegex);
	}

	[Fact(DisplayName="unit/general/enum_out_of_range_2.mzn")]
	public async Task test_solve_unit_general_enum_out_of_range_2()
	{
		var path = "unit/general/enum_out_of_range_2.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = ".*declared domain of `x' is {A}, but assigned value is {B}.*";
		await Test(path, solver, errorMessage, errorRegex);
	}

	[Fact(DisplayName="unit/general/function_param_out_of_range.mzn")]
	public async Task test_solve_unit_general_function_param_out_of_range()
	{
		var path = "unit/general/function_param_out_of_range.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = ".*declared domain of `'<unnamed argument>'' is 1..1, but assigned value is 2.*";
		await Test(path, solver, errorMessage, errorRegex);
	}

	[Fact(DisplayName="unit/general/function_return_out_of_range.mzn")]
	public async Task test_solve_unit_general_function_return_out_of_range()
	{
		var path = "unit/general/function_return_out_of_range.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = ".*result of function `foo' is B, which violates function type-inst {A}.*";
		await Test(path, solver, errorMessage, errorRegex);
	}

	[Fact(DisplayName="unit/general/function_return_out_of_range_opt.mzn")]
	public async Task test_solve_unit_general_function_return_out_of_range_opt()
	{
		var path = "unit/general/function_return_out_of_range_opt.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = ".*function result violates function type-inst, array contains value B which is not contained in {A}.*";
		await Test(path, solver, errorMessage, errorRegex);
	}

	[Fact(DisplayName="unit/general/param_out_of_range_float.mzn")]
	public async Task test_solve_unit_general_param_out_of_range_float()
	{
		var path = "unit/general/param_out_of_range_float.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = ".*declared domain of `x' is -infinity..-1.0 union 1.0..infinity, but assigned value is 0.0.*";
		await Test(path, solver, errorMessage, errorRegex);
	}

	[Fact(DisplayName="unit/general/param_out_of_range_int.mzn")]
	public async Task test_solve_unit_general_param_out_of_range_int()
	{
		var path = "unit/general/param_out_of_range_int.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = ".*declared domain of `x' is -infinity..-1 union 1..infinity, but assigned value is 0.*";
		await Test(path, solver, errorMessage, errorRegex);
	}

	[Fact(DisplayName="unit/general/stack_overflow.mzn")]
	public async Task test_solve_unit_general_stack_overflow()
	{
		var path = "unit/general/stack_overflow.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = ".*stack overflow.*";
		await Test(path, solver, errorMessage, errorRegex);
	}

	[Fact(DisplayName="unit/json/anon_enum_json.mzn")]
	public async Task test_solve_unit_json_anon_enum_json_2()
	{
		var path = "unit/json/anon_enum_json.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = ".*invalid enum object.*";
		await Test(path, solver, errorMessage, errorRegex,"--data \"unit/json/anon_enum_json_err.json\"");
	}

	[Fact(DisplayName="unit/json/coerce_enum_str_err.mzn")]
	public async Task test_solve_unit_json_coerce_enum_str_err()
	{
		var path = "unit/json/coerce_enum_str_err.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = ".*has invalid type-inst.*";
		await Test(path, solver, errorMessage, errorRegex,"--data \"unit/json/coerce_enum_str_err.json\"");
	}

	[Fact(DisplayName="unit/param_file/param_file_blacklist.mzn")]
	public async Task test_solve_unit_param_file_param_file_blacklist()
	{
		var path = "unit/param_file/param_file_blacklist.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = ".*not allowed in configuration file.*";
		await Test(path, solver, errorMessage, errorRegex,"--data \"unit/param_file/param_file_blacklist_1.mpc\"");
	}

	[Fact(DisplayName="unit/param_file/param_file_blacklist.mzn")]
	public async Task test_solve_unit_param_file_param_file_blacklist_2()
	{
		var path = "unit/param_file/param_file_blacklist.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = ".*not allowed in configuration file.*";
		await Test(path, solver, errorMessage, errorRegex,"--data \"unit/param_file/param_file_blacklist_2.mpc\"");
	}

	[Fact(DisplayName="unit/param_file/param_file_recursive.mzn")]
	public async Task test_solve_unit_param_file_param_file_recursive()
	{
		var path = "unit/param_file/param_file_recursive.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = ".*Cyclic parameter configuration file.*";
		await Test(path, solver, errorMessage, errorRegex,"--data \"unit/param_file/param_file_recursive.mpc\"");
	}

	[Fact(DisplayName="unit/regression/cyclic_include.mzn")]
	public async Task test_solve_unit_regression_cyclic_include()
	{
		var path = "unit/regression/cyclic_include.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = null;
		await Test(path, solver, errorMessage, errorRegex);
	}

	[Fact(DisplayName="unit/regression/github_648_par_array_decl.mzn")]
	public async Task test_solve_unit_regression_github_648_par_array_decl()
	{
		var path = "unit/regression/github_648_par_array_decl.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = ".*declared domain of `x[1]' is 1..3, but assigned value is 0.*";
		await Test(path, solver, errorMessage, errorRegex);
	}

	[Fact(DisplayName="unit/regression/github_648_par_decl.mzn")]
	public async Task test_solve_unit_regression_github_648_par_decl()
	{
		var path = "unit/regression/github_648_par_decl.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = ".*declared domain of `x' is 1..3, but assigned value is 0.*";
		await Test(path, solver, errorMessage, errorRegex);
	}

	[Fact(DisplayName="unit/regression/github_656.mzn")]
	public async Task test_solve_unit_regression_github_656()
	{
		var path = "unit/regression/github_656.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = ".*cannot coerce set into 2-dimensional array.*";
		await Test(path, solver, errorMessage, errorRegex);
	}

	[Fact(DisplayName="unit/regression/github_680.mzn")]
	public async Task test_solve_unit_regression_github_680()
	{
		var path = "unit/regression/github_680.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = null;
		await Test(path, solver, errorMessage, errorRegex);
	}

	[Fact(DisplayName="unit/regression/github_725.mzn")]
	public async Task test_solve_unit_regression_github_725()
	{
		var path = "unit/regression/github_725.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = null;
		await Test(path, solver, errorMessage, errorRegex);
	}

	[Fact(DisplayName="unit/regression/github_730.mzn")]
	public async Task test_solve_unit_regression_github_730()
	{
		var path = "unit/regression/github_730.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = null;
		await Test(path, solver, errorMessage, errorRegex);
	}

	[Fact(DisplayName="unit/regression/github_779.mzn")]
	public async Task test_solve_unit_regression_github_779()
	{
		var path = "unit/regression/github_779.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = null;
		await Test(path, solver, errorMessage, errorRegex);
	}

	[Fact(DisplayName="unit/regression/non-set-array-ti-location.mzn")]
	public async Task test_solve_unit_regression_non_set_array_ti_location()
	{
		var path = "unit/regression/non-set-array-ti-location.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = null;
		await Test(path, solver, errorMessage, errorRegex);
	}

	[Fact(DisplayName="unit/regression/output_only_no_rhs.mzn")]
	public async Task test_solve_unit_regression_output_only_no_rhs()
	{
		var path = "unit/regression/output_only_no_rhs.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = null;
		await Test(path, solver, errorMessage, errorRegex);
	}

	[Fact(DisplayName="unit/regression/parser_location.mzn")]
	public async Task test_solve_unit_regression_parser_location()
	{
		var path = "unit/regression/parser_location.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = null;
		await Test(path, solver, errorMessage, errorRegex);
	}

	[Fact(DisplayName="unit/regression/test_parout.mzn")]
	public async Task test_solve_unit_regression_test_parout_2()
	{
		var path = "unit/regression/test_parout.mzn";
		var solver = "coin-bc";
		string? errorMessage = null;
		string? errorRegex = null;
		await Test(path, solver, errorMessage, errorRegex);
	}

	[Fact(DisplayName="unit/regression/ti_error_location.mzn")]
	public async Task test_solve_unit_regression_ti_error_location()
	{
		var path = "unit/regression/ti_error_location.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = "^(?!unknown file:0.0).*$";
		await Test(path, solver, errorMessage, errorRegex);
	}

	[Fact(DisplayName="unit/types/alias_set_of_array.mzn")]
	public async Task test_solve_unit_types_alias_set_of_array()
	{
		var path = "unit/types/alias_set_of_array.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = null;
		await Test(path, solver, errorMessage, errorRegex);
	}

	[Fact(DisplayName="unit/types/array_var_opt_set_comprehension.mzn")]
	public async Task test_solve_unit_types_array_var_opt_set_comprehension()
	{
		var path = "unit/types/array_var_opt_set_comprehension.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = null;
		await Test(path, solver, errorMessage, errorRegex);
	}

	[Fact(DisplayName="unit/types/comprehension_of_absent_any_1.mzn")]
	public async Task test_solve_unit_types_comprehension_of_absent_any_1()
	{
		var path = "unit/types/comprehension_of_absent_any_1.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = null;
		await Test(path, solver, errorMessage, errorRegex);
	}

	[Fact(DisplayName="unit/types/nested_type_inst_id.mzn")]
	public async Task test_solve_unit_types_nested_type_inst_id()
	{
		var path = "unit/types/nested_type_inst_id.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = ".*type-inst variable $X used in both array and non-array position.*";
		await Test(path, solver, errorMessage, errorRegex);
	}

	[Fact(DisplayName="unit/types/nonbool_constraint.mzn")]
	public async Task test_solve_unit_types_nonbool_constraint()
	{
		var path = "unit/types/nonbool_constraint.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = null;
		await Test(path, solver, errorMessage, errorRegex);
	}

	[Fact(DisplayName="unit/types/nonbool_constraint_let.mzn")]
	public async Task test_solve_unit_types_nonbool_constraint_let()
	{
		var path = "unit/types/nonbool_constraint_let.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = null;
		await Test(path, solver, errorMessage, errorRegex);
	}

	[Fact(DisplayName="unit/types/record_access_error.mzn")]
	public async Task test_solve_unit_types_record_access_error()
	{
		var path = "unit/types/record_access_error.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = null;
		await Test(path, solver, errorMessage, errorRegex);
	}

	[Fact(DisplayName="unit/types/record_array_access_error.mzn")]
	public async Task test_solve_unit_types_record_array_access_error()
	{
		var path = "unit/types/record_array_access_error.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = null;
		await Test(path, solver, errorMessage, errorRegex);
	}

	[Fact(DisplayName="unit/types/record_decl_error.mzn")]
	public async Task test_solve_unit_types_record_decl_error()
	{
		var path = "unit/types/record_decl_error.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = null;
		await Test(path, solver, errorMessage, errorRegex);
	}

	[Fact(DisplayName="unit/types/record_ite_error.mzn")]
	public async Task test_solve_unit_types_record_ite_error()
	{
		var path = "unit/types/record_ite_error.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = null;
		await Test(path, solver, errorMessage, errorRegex);
	}

	[Fact(DisplayName="unit/types/record_lit_dup.mzn")]
	public async Task test_solve_unit_types_record_lit_dup()
	{
		var path = "unit/types/record_lit_dup.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = null;
		await Test(path, solver, errorMessage, errorRegex);
	}

	[Fact(DisplayName="unit/types/struct_index_sets_1.mzn")]
	public async Task test_solve_unit_types_struct_index_sets_1()
	{
		var path = "unit/types/struct_index_sets_1.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = ".* Declared index set of `x.1' is [1..1], but is assigned to array with index set [2..2].*";
		await Test(path, solver, errorMessage, errorRegex);
	}

	[Fact(DisplayName="unit/types/struct_index_sets_2.mzn")]
	public async Task test_solve_unit_types_struct_index_sets_2()
	{
		var path = "unit/types/struct_index_sets_2.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = ".* Declared index set of `x.1' is [1..1], but is assigned to array with index set [2..2].*";
		await Test(path, solver, errorMessage, errorRegex);
	}

	[Fact(DisplayName="unit/types/struct_return_ti_3.mzn")]
	public async Task test_solve_unit_types_struct_return_ti_3()
	{
		var path = "unit/types/struct_return_ti_3.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = ".*function result violates function type-inst.*";
		await Test(path, solver, errorMessage, errorRegex);
	}

	[Fact(DisplayName="unit/types/tuple_access_error1.mzn")]
	public async Task test_solve_unit_types_tuple_access_error1()
	{
		var path = "unit/types/tuple_access_error1.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = null;
		await Test(path, solver, errorMessage, errorRegex);
	}

	[Fact(DisplayName="unit/types/tuple_access_error2.mzn")]
	public async Task test_solve_unit_types_tuple_access_error2()
	{
		var path = "unit/types/tuple_access_error2.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = null;
		await Test(path, solver, errorMessage, errorRegex);
	}

	[Fact(DisplayName="unit/types/tuple_array_access_error.mzn")]
	public async Task test_solve_unit_types_tuple_array_access_error()
	{
		var path = "unit/types/tuple_array_access_error.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = null;
		await Test(path, solver, errorMessage, errorRegex);
	}

	[Fact(DisplayName="unit/types/tuple_ite_error.mzn")]
	public async Task test_solve_unit_types_tuple_ite_error()
	{
		var path = "unit/types/tuple_ite_error.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = null;
		await Test(path, solver, errorMessage, errorRegex);
	}

	[Fact(DisplayName="unit/types/var_ann_a.mzn")]
	public async Task test_solve_unit_types_var_ann_a()
	{
		var path = "unit/types/var_ann_a.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = null;
		await Test(path, solver, errorMessage, errorRegex);
	}

	[Fact(DisplayName="unit/types/var_ann_b.mzn")]
	public async Task test_solve_unit_types_var_ann_b()
	{
		var path = "unit/types/var_ann_b.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = null;
		await Test(path, solver, errorMessage, errorRegex);
	}

	[Fact(DisplayName="unit/types/var_ann_comprehension.mzn")]
	public async Task test_solve_unit_types_var_ann_comprehension()
	{
		var path = "unit/types/var_ann_comprehension.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = null;
		await Test(path, solver, errorMessage, errorRegex);
	}

	[Fact(DisplayName="unit/types/var_opt_set_if_then_else.mzn")]
	public async Task test_solve_unit_types_var_opt_set_if_then_else()
	{
		var path = "unit/types/var_opt_set_if_then_else.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = null;
		await Test(path, solver, errorMessage, errorRegex);
	}

	[Fact(DisplayName="unit/types/var_set_bool.mzn")]
	public async Task test_solve_unit_types_var_set_bool()
	{
		var path = "unit/types/var_set_bool.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = null;
		await Test(path, solver, errorMessage, errorRegex);
	}

	[Fact(DisplayName="unit/types/var_set_float.mzn")]
	public async Task test_solve_unit_types_var_set_float()
	{
		var path = "unit/types/var_set_float.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = null;
		await Test(path, solver, errorMessage, errorRegex);
	}

	[Fact(DisplayName="unit/types/var_set_float_comprehension.mzn")]
	public async Task test_solve_unit_types_var_set_float_comprehension()
	{
		var path = "unit/types/var_set_float_comprehension.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = null;
		await Test(path, solver, errorMessage, errorRegex);
	}

	[Fact(DisplayName="unit/types/var_string_a.mzn")]
	public async Task test_solve_unit_types_var_string_a()
	{
		var path = "unit/types/var_string_a.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = null;
		await Test(path, solver, errorMessage, errorRegex);
	}

	[Fact(DisplayName="unit/types/var_string_b.mzn")]
	public async Task test_solve_unit_types_var_string_b()
	{
		var path = "unit/types/var_string_b.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = null;
		await Test(path, solver, errorMessage, errorRegex);
	}

	[Fact(DisplayName="unit/types/var_string_comprehension.mzn")]
	public async Task test_solve_unit_types_var_string_comprehension()
	{
		var path = "unit/types/var_string_comprehension.mzn";
		var solver = "gecode";
		string? errorMessage = null;
		string? errorRegex = null;
		await Test(path, solver, errorMessage, errorRegex);
	}

}

