/*
<auto-generated>
This file has been auto generated by the following command:
dotnet run --project ./build/Make/Make.csproj --make-client-tests
</auto-generated>
*/
#nullable enable

public class ErrorTests : ClientTest
{

	public ErrorTests(ITestOutputHelper output, ClientFixture fixture) : base(output, fixture)
	{
	}

}

