name: Build master

on: [push, pull_request]

jobs:
  test-parse:
    runs-on:
      ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
      - run: dotnet restore
      - run: dotnet build src/MiniZinc.Model/MiniZinc.Model.fsproj --no-restore
      - run: dotnet test tests/MiniZinc.ModelTests/MiniZinc.ModelTests.fsproj --no-build --verbosity normal

  test-solve:
    runs-on:
      ubuntu-latest
    strategy:
      matrix:
        minizinc-version: ["2.7.4", "2.5.4"]
      fail-fast:
        false        
    env:
      MINIZINC_URL: https://github.com/MiniZinc/MiniZincIDE/releases/download/${{ matrix.minizinc-version }}/MiniZincIDE-${{ matrix.minizinc-version }}-x86_64.AppImage
    steps:
      - uses: actions/checkout@v3
      - name: Add bin/ to PATH
        run: |
          mkdir -p ${{ github.workspace }}/bin
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH
      - name: Install libfuse (AppImage dependency)
        run: |
          sudo apt-get update
          sudo apt-get install libfuse2 libegl1
      - name: Cache MiniZinc
        id: cache-minizinc
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/bin/minizinc
          key: ${{ env.MINIZINC_URL }}
      - name: Download MiniZinc
        if: steps.cache-minizinc.outputs.cache-hit != 'true'
        run: |
          sudo curl -o ${{ github.workspace }}/bin/minizinc -L $MINIZINC_URL
          sudo chmod +x ${{ github.workspace }}/bin/minizinc
          minizinc --version
      - uses: actions/setup-dotnet@v3
      - run: dotnet restore
      - run: dotnet build src/MiniZinc.Solve/MiniZinc.Solve.fsproj --no-restore
      - run: dotnet test tests/MiniZinc.SolveTests --no-build --verbosity normal