name: Test

on:
  push:    
    branches: 
      - master
      
jobs:
  tests:
    name:
      Build and Test
    runs-on:
      ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: docker build . --tag mzn
      
      - name: Run
        run: docker run mzn